fun main(args: Array<String>) {
    val tvSony = TV("Sony","sh-20",33.0f)
    tvSony.enableOrDisable()
    tvSony.listAllChannel()
    tvSony.switchChannel(3)
    tvSony.enableOrDisable()
    tvSony.switchChannel(2)
    tvSony.enableOrDisable()
    for (i in 1..5) tvSony.channelUp()
    for (i in 1..5) tvSony.volUp(33)
    for (i in 1..5) tvSony.volDown(32)
    tvSony.enableOrDisable()
    for (i in 1..5) tvSony.channelDown()

    val tvDexp = TV("Dexp","xxx-007",50.0f)
    tvDexp.enableOrDisable()
    tvDexp.listAllChannel()
    tvDexp.switchChannel(1)
    tvDexp.enableOrDisable()
    tvDexp.switchChannel(4)
    tvDexp.enableOrDisable()
    for (i in 1..5) tvDexp.channelUp()
    for (i in 1..5) tvDexp.volUp(28)
    for (i in 1..5) tvDexp.volDown(25)
    tvDexp.enableOrDisable()
    for (i in 1..5) tvDexp.channelDown()
}